TeamFourA/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using TeamFourA.Services;
using TeamFourA.Models;
using TeamFourA.Db;

namespace TeamFourA.Controllers
{
    //shermaine
    public class LoginController : Controller
    {
        protected Users users;
        protected Dictionary<string, StringTable> dict;
        private ShoppingContext dbcontext;
        public LoginController(ShoppingContext dbcontext, Dictionary<string, StringTable> dict, Users users)
        {
            this.dict = dict;
            this.users = users;
            this.dbcontext = dbcontext;

        }

        public IActionResult Index(string locale)
        {
            StringTable stringTbl;
            if (locale != null)
            {
                dict.TryGetValue(locale, out stringTbl);
                Response.Cookies.Append("locale", locale);
            }
            else if (Request.Cookies["locale"] != null)
                dict.TryGetValue(Request.Cookies["locale"], out stringTbl);
            else
            {
                dict.TryGetValue("en", out stringTbl);
                Response.Cookies.Append("locale", "en");
            }

            ViewData["err"] = TempData["err"];
            ViewData["StringTbl"] = stringTbl;
            return View();
        }

        public IActionResult Login([FromServices] Users users, string username, string hashPasswd)
        {
            StringTable stringTbl;

            dict.TryGetValue(Request.Cookies["locale"], out stringTbl);
            //string pass = "hello";
            User user = users.AuthenticateUser(username, hashPasswd, dbcontext);
            if (user==null)
            {
                TempData["err"] = stringTbl.loginfail;
                return RedirectToAction("Index");
            }

            Response.Cookies.Append("sessionId", Guid.NewGuid().ToString(),
                new CookieOptions()
                {
                    Expires = DateTimeOffset.UtcNow.AddSeconds(30)
                });

            HttpContext.Session.SetString("username", username);

            TempData["username"] = username;
            return RedirectToAction("Index", "Home");
        }
    }
}

TeamFourA/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TeamFourA.Controllers
{
    //shermaine
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {
            Response.Cookies.Delete("sessionId");

            TempData.Clear();
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Login");
        }
    }
}

TeamFourA/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TeamFourA.Db;
using TeamFourA.Models;
using TeamFourA.Services;

namespace TeamFourA.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ShoppingContext _dbContext;
        private readonly ProductIds _productIds;

        public ProductsController(ShoppingContext shoppingContext, ProductIds productIds)
        {
            _dbContext = shoppingContext;
            _productIds = productIds;
        }

        public IActionResult Index(string productId)
        {
            // generate sessionId using guid
            var sessionId = HttpContext.Session.GetString("sessionId");

            if (sessionId == null)
                sessionId = Guid.NewGuid().ToString();

            // store sessionId in session
            HttpContext.Session.SetString("sessionId", sessionId);

            // if productId != null, add productId to session
            if (productId != null)
            {
                var preProductIds = HttpContext.Session.GetString("productIds");
                var postProductIds = _productIds.AddId(preProductIds, productId);
                HttpContext.Session.SetString("productIds", postProductIds);

                var badge = HttpContext.Session.GetString("Badge");

                if(badge == null)
                {
                    string[] ids = postProductIds.Split(";");
                    HttpContext.Session.SetString("Badge", ids.Length.ToString());

                } else
                {
                    string[] ids = postProductIds.Split(";");
                    HttpContext.Session.SetString("Badge", ids.Length.ToString());
                }
            }

            var model = new ProductsViewModel
            {
                Products = _dbContext.Products
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(ProductsViewModel model)
        {
            if (!String.IsNullOrEmpty(model.Text))
            {

                model.Products = _dbContext.Products
                    .Where(p => p.Name.Contains(model.Text) ||
                                p.Description.Contains(model.Text));
            }
            else
            {
                model.Products = _dbContext.Products;
            }

            return View(model);
        }

    }
}

TeamFourA/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TeamFourA.Db;
using TeamFourA.Models;
using TeamFourA.Services;

namespace TeamFourA.Controllers
{
    //shermaine
    public class RegisterController : Controller
    {
        protected Users users;
        protected Dictionary<string, StringTable> dict;
        private ShoppingContext dbcontext;
    

        public RegisterController(ShoppingContext dbcontext, Dictionary<string, StringTable>dict, Users user)
        {
             
            this.dbcontext = dbcontext;
            this.users = user;
            this.dict = dict;
        }

        public IActionResult Index(string locale)
        {
            StringTable stringTbl;

            if (locale != null)
            {
                dict.TryGetValue(locale, out stringTbl);
                Response.Cookies.Append("locale", locale);
            }
            else
                dict.TryGetValue(Request.Cookies["locale"], out stringTbl);

            ViewData["err"] = TempData["err"];
            ViewData["username"] = TempData["username"];
            ViewData["stringTbl"] = stringTbl;

            return View();
        }

        public IActionResult Register(string username, string hashPasswd)
        {
            StringTable stringTbl;
            dict.TryGetValue(Request.Cookies["locale"], out stringTbl);

            User user = users.GetUser(username, dbcontext);
            if (user != null)
            {
                TempData["err"] = stringTbl.username_taken;
                TempData["username"] = username;

                return RedirectToAction("Index");
            }

            users.AddUser(new User()
            {
                Username = username,
                Password = hashPasswd
            }, dbcontext);

            ViewData["username"] = username;
            ViewData["stringTbl"] = stringTbl;
            return View();
        }

        public IActionResult IsUsernameAvailable([FromBody] User inUser)
        {
            User user = users.GetUser(inUser.Username, dbcontext);

            return Json(user == null);
        }
    }
}

TeamFourA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeamFourA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
</head>
<body>
    @{
        @using Microsoft.AspNetCore.Http
        String bagde = Context.Session.GetString("Badge");
        String username = Context.Session.GetString("username");

    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TeamFourA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            @{
                                if (bagde != null)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Cart <span class="badge badge-dark">@bagde</span></a>
                                }
                                else
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Cart <span class="badge badge-dark">0</span></a>

                                }
                            }
                        </li>
                        @{
                            if (username == null)
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="">Register</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Purchases" asp-action="Index">Purchase History</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a>
                                </li>
                                <li class="nav-item" style="padding: .5rem 1rem;">
                                    Welcome @username!
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TeamFourA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/crypto/core-min.js"></script>
    <script src="~/lib/crypto/sha256.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TeamFourA/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeamFourA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TeamFourA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TeamFourA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/crypto/core-min.js"></script>
    <script src="~/lib/crypto/sha256.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>